# Generated by Django 4.2.1 on 2023-07-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
